version: '3.8'
services:
  hash-server:
    ports:
      - 12345:12345
    build:
      dockerfile: ../Dockerfile
    volumes:
      - ..:/workspaces:cached
      - /Users/evgenii/.ssh:/home/vscode/.ssh:cached
    command: sleep infinity
